<a href="https://colab.research.google.com/github/akhilavantakula/special-octo-computing-machine/blob/main/MLP_NPPE_2_MODEL_BUILDING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
df=pd.read_csv('/content/T124OPPE2_ModelBuilding_V1.csv')
x,y=df.iloc[:,:-1],df.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,shuffle=False)

Instructions (Q2-Q3)
Instantiate a perceptron classifier that with following parameters:

	random_state = 1729
	learning rate = 1
	Train for appropriate number of iterations
	Do not shuffle the dataset for each iteration.
	Include the intercept (bias) term.
	Use 10% of the data for validation fraction.
	Do not apply regularization.
	Set warm start to true.

Hint: one iteration of training indicates going over each sample exactly once.

Train the classifier on the training data.


Train the perceptron classifier for 5 iterations. What is value of bias (intercept) after 5th iteration?

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
perceptron=Perceptron(
    random_state = 1729,
    eta0 = 1,
    shuffle =False,
    fit_intercept=True,
    validation_fraction=0.1,
    penalty=None,
    warm_start=True
)
for i in range(5):
  perceptron.partial_fit(x_train,y_train,classes=np.unique(y_train))
perceptron.intercept_

array([-3.])


In continuation of the previous question, compute precision accurate upto 2 decimal places on training data for positive class (i.e. class value 1), after 5 iterations.

[Hint: Use estimator trained from the previous question]


In [ ]:
from sklearn.metrics import precision_score
y_pred=perceptron.predict(x_train)
precision_score(y_train,y_pred,pos_label=1,zero_division=0)

0.6666666666666666

Train (on training data only) logistic regression using SGDClassifier. Use the following parameters:

	Choose appropriate loss value to obtain logistic regression
	penalty='l2',
	eta0=0.001,
	alpha=0,
	learning_rate='constant'
	random_state=1729.
	warm_start = True

Train the classifier for 5 iterations and note the value of the loss in each iteration. What will be the loss value after second iteration? Answer upto three decimal places.

Note: Set the remaining parameters, if any, accordingly to be able to get the loss value after second iteration. Also note that the classifier has to be trained for 5 iterations.

In [ ]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import log_loss
sgd=SGDClassifier(
    loss='log_loss',
    penalty='l2',
    eta0=0.001,
    alpha=0,
    learning_rate='constant',
    random_state=1729,
    warm_start=True,
)
loss_value=[]
for i in range(5):
  sgd.partial_fit(x_train,y_train,classes=np.unique(y_train))
  y_pred_proba = sgd.predict_proba(x_train)
  loss = log_loss(y_train, y_pred_proba)
  loss_value.append(loss)
loss_value

[0.2529904609012919,
 0.20828682141739835,
 0.19406901833322654,
 0.18699850891012404,
 0.18255077295024025]


1 point
Use GridSearchCV with SGDClassifier. Following are the classifier's parameters:

	loss = 'log_loss'
	learning_rate = 'constant'
	random_state = 1729

Following are parameters to examine:

	alpha = [0.0001, 0.0005, 0.001, 0.005]
	eta0 = [0.01, 0.05, 0.1, 0.5]

What are the best values of alpha and eta0 respectively?

In [ ]:
from sklearn.model_selection import GridSearchCV
param_grid={
    'alpha':[0.0001, 0.0005, 0.001, 0.005],
    'eta0' : [0.01, 0.05, 0.1, 0.5]
}
classifer=SGDClassifier(
    loss = 'log_loss',
    learning_rate = 'constant',
    random_state = 1729
)
grid_search=GridSearchCV(
    estimator=classifer,
    param_grid=param_grid,
)
grid_search.fit(x_train,y_train)
grid_search.best_params_

{'alpha': 0.0001, 'eta0': 0.01}

Create a new estimator using SGDClassifier that uses the best parameters obtained in Gridsearch earlier ((learning rate to be constant, random_state to be '1729' and use appropriate loss for logistic regression)) and set the weight of class 0 to be 0.1 and the weight of class 1 to be 2. How many samples of class 1 from the test set are correctly predicted by this estimator?

In [ ]:
from sklearn.metrics import confusion_matrix
sgd_classifier=SGDClassifier(
    loss='log_loss',
    learning_rate='constant',
    random_state=1729,
    alpha=0.0001,
    eta0=0.01,
    class_weight={0:0.1,1:2}
)
sgd_classifier.fit(x_train,y_train)
y_pred=sgd_classifier.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[843, 299],
       [ 11,  47]])

Fit an SVM classifier with following parameters:

	kernel='rbf'
	decision_function_shape='ovr'
	random_state=1729
	C=1

Train the model on training data, and print the confusion matrix on test data.

In [ ]:
from sklearn.svm import SVC
svm=SVC(
    kernel='rbf',
	  decision_function_shape='ovr',
	  random_state=1729,
	  C=1
)
svm.fit(x_train,y_train)
y_pred=svm.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[1142,    0],
       [  58,    0]])

Train a Decision Tree Classifier with the following properties:

	criterion = 'entropy',
	splitter = 'random',
	min_samples_split = 4,
	min_impurity_decrease = 0.0001,
	random_state = 1729

What is the resultant depth of the tree?
How many nodes are there in the tree?

In [ ]:
from sklearn.tree import DecisionTreeClassifier
decision_tree=DecisionTreeClassifier(
    criterion = 'entropy',
    splitter = 'random',
    min_samples_split = 4,
    min_impurity_decrease = 0.0001,
    random_state = 1729
)
decision_tree.fit(x_train,y_train)
print(decision_tree.get_depth(),decision_tree.tree_.node_count)

20 515


What is the value of entropy at the left child of root?

In [ ]:
decision_tree.tree_.impurity[decision_tree.tree_.children_left[0]]

0.024564134553940277

Out of DecisionTreeClassifier, KNeighborsClassifier and LogisticRegression, which one performs the best when used as base estimator in BaggingClassifier on the test data in terms of accuracy score when 20 base estimators are used ?
(Use random state 1729 for BaggingClassifier, DecisionTreeClassifier and LogisticRegression)

The metric for best performance will be the lowest 'absolute' difference in the train and test score.

DecisionTreeClassifie

KNeighborsClassifier

LogisticRegression

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
dtc=DecisionTreeClassifier(random_state=1729)
knc=KNeighborsClassifier()
lr=LogisticRegression(random_state=1729)
bagging_dtc=BaggingClassifier(
    base_estimator=dtc,
    n_estimators=20,
    random_state=1729)
bagging_knc=BaggingClassifier(
    base_estimator=knc,
    n_estimators=20,
    random_state=1729)
bagging_lr=BaggingClassifier(
    base_estimator=lr,
    n_estimators=20,
    random_state=1729)
bagging_dtc.fit(x_train,y_train)
bagging_knc.fit(x_train,y_train)
bagging_lr.fit(x_train,y_train)
y_pred_dtc=bagging_dtc.predict(x_test)
y_pred_knc=bagging_knc.predict(x_test)
y_pred_lr=bagging_lr.predict(x_test)
print(accuracy_score(y_test,y_pred_dtc))
print(accuracy_score(y_test,y_pred_knc))
print(accuracy_score(y_test,y_pred_lr))

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


0.9441666666666667
0.9508333333333333
0.9516666666666667


When the above three individual classifiers (with same settings) are used in VotingClassifier, how much absolute difference do we obtain in train and test scores? Enter your answer correct upto 4 decimal places.

In [ ]:
from sklearn.ensemble import VotingClassifier
dt_classifier = DecisionTreeClassifier(random_state=1729)
knn_classifier = KNeighborsClassifier()
lr_classifier = LogisticRegression(random_state=1729)
voting_clf = VotingClassifier(
    estimators=[
        ('dt', dt_classifier),
        ('knn', knn_classifier),
        ('lr', lr_classifier)
    ],
    voting='hard'
)
voting_clf.fit(x_train, y_train)
y_train_pred = voting_clf.predict(x_train)
y_test_pred = voting_clf.predict(x_test)
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)
absolute_difference = abs(train_accuracy - test_accuracy)
print(f"Absolute difference between train and test scores: {absolute_difference:.4f}")

Absolute difference between train and test scores: 0.0043
